#ifndef _CONSTANCE_H
#define _CONSTANCE_H

#define SERVER_ADDR "127.0.0.1"
#define SERVER_PORT 8080
#define SOCK_DEFAULT_PROTOCOL 0
#define HTTP_STATUS_OK 200
#define HTTP_STATUS_NOT_FOUND 404
#define HTTP_STATUS_ERROR 500
#define HTTP_OK_MESSAGE "OK"
#define HTTP_NOT_FOUND_MESSAGE "Not Found"
#define HTTP_SERVER_ERROR "Error"
#define HTTP_VERSION "HTTP/1.1"
#define ERROR_FLAG -1
#define SUCCESS_FLAG 0
#define NUM_OF_CONNECT_KEEP 3
#endif
